trigger:
- master

pool:
  name: 'Default'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
    checkLatest: true
  displayName: 'Install Node.js'

- script: |
    sudo npm install vite --save-dev
    sudo npm install @vitejs/plugin-react --save-dev
  displayName: 'Install Vite and @vitejs/plugin-react'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/build' # Update with your build output directory
    artifactName: 'react-app'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'
